user root

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log

# Disable anonymous access
allow_anonymous false

# Password authentication
password_file /mosquitto/config/passwordfile

# Disable non-TLS port (OPTIONAL but recommended)
# listener 1883

# TLS listener
listener 8883

cafile /mosquitto/certs/server.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key

require_certificate false
tls_version tlsv1.2